[[main]]
none = "none"

[[main]]
name = "Blog"
pageRef = "posts"
pre = "comment"
identifier = "hFLLmtecPq"
weight = 9_999

[[main]]
name = "CTFs"
pre = "bomb"
pageRef = "ctfs"
identifier = "X01TxeUmpl"
weight = 9_999

[[main]]
name = "HTB"
pageRef = "ctfs/htb"
weight = 11
parent = "X01TxeUmpl"

[[main]]
name = "OffSec"
pageRef = "ctfs/offsec"
weight = 11
parent = "X01TxeUmpl"

[[main]]
name = "THM"
pageRef = "ctfs/thm"
weight = 11
parent = "X01TxeUmpl"


[[main]]
name = "Projects"
pre = "lightbulb"
pageRef = "projects"
identifier = "estl7adWl3"
weight = 9_999


[[main]]
name = "University Projects"
pageRef = "projects/university"
weight = 11
parent = "estl7adWl3"


[[main]]
name = "Personal Projects"
pageRef = "projects/personal"
weight = 12
parent = "estl7adWl3"


[[footer]]
none = "none"
